branches:
  master:
    type: stable
    paper: "26.2"
    java: "25"
  main:
    type: stable
    paper: "26.2"
    java: "25"
  beta:
    type: beta
    paper: "26.2"
    java: "25"
  paper-26.3:
    type: test
    paper: "26.3"
    java: "25"