# SimpleBackpack configuration file
# Language: en (en/de)
language: en

# === General Features ===
classic-mode: false           # Only /backpack and /bp are enabled, all other features hidden
backpacks-enabled: true       # Enable/disable all backpack features globally
live-config-reload: true      # Allow live reload of config with /backpackreload
stats-enabled: true           # If false, disables all stats reporting to dashboard

# === Backpack Settings ===
backpack:
  name: "\u00a7bSimple Backpack" # Inventory name in Aqua color
  size: 27                    # Possible values: 9, 18, 27, 36, 45, 54
  allow-in-creative: false    # If true, players can use backpack in creative mode
  auto-save-on-quit: true     # Automatically save backpack when player disconnects
  keep-on-death: true         # If true, backpack contents are kept on death
  gui-configurable: true      # If true, players can configure backpack via GUI

# === Team Settings ===
team:
  enabled: true
  max-size: 5                 # Maximum number of players per team

# === Admin Settings ===
admin:
  enabled: true               # Enable admin features (global enable/disable, give items, etc)

# === Command Visibility ===
show-team-commands: true      # Show/hide all team commands
show-admin-commands: true     # Show/hide all admin commands

# === Messaging ===
messages-enabled: true        # If false, no messages will be sent to players

messages:
  en:
    open-success: "\u00a7bYour backpack is now open!"
    no-permission: "\u00a7cYou do not have permission to use this command."
    not-allowed-world: "\u00a7cYou cannot use your backpack in this world."
    creative-not-allowed: "\u00a7cBackpack is not available in Creative mode."
    reload-success: "\u00a7aConfig reloaded successfully."
    first-join: "\u00a7eWelcome! Use /backpack to open your personal backpack. You can share it with your team and configure it via /backpackconfig."
    team-invite: "\u00a7aYou have invited {player} to your team."
    team-joined: "\u00a7aYou have joined the team!"
    team-full: "\u00a7cYour team is full."
    team-share: "\u00a7bYou are now sharing your backpack with your team."
    team-leave: "\u00a7aYou have left the team."
    not-in-team: "\u00a7cYou are not in a team."
    config-changed: "\u00a7aBackpack configuration updated."
    backpacks-disabled: "\u00a7cBackpacks are currently disabled by an admin."
    admin-giveall: "\u00a7aItem given to all backpacks."
    admin-enabled: "\u00a7aBackpacks globally enabled."
    admin-disabled: "\u00a7cBackpacks globally disabled."
  de:
    open-success: "\u00a7bDein Rucksack ist jetzt ge\u00f6ffnet!"
    no-permission: "\u00a7cDu hast keine Berechtigung f\u00fcr diesen Befehl."
    not-allowed-world: "\u00a7cDu kannst deinen Rucksack in dieser Welt nicht benutzen."
    creative-not-allowed: "\u00a7cRucksack ist im Kreativmodus nicht verf\u00fcgbar."
    reload-success: "\u00a7aKonfiguration erfolgreich neu geladen."
    first-join: "\u00a7eWillkommen! Nutze /backpack, um deinen pers\u00f6nlichen Rucksack zu \u00f6ffnen. Du kannst ihn mit deinem Team teilen und \u00fcber /backpackconfig konfigurieren."
    team-invite: "\u00a7aDu hast {player} in dein Team eingeladen."
    team-joined: "\u00a7aDu bist dem Team beigetreten!"
    team-full: "\u00a7cDein Team ist voll."
    team-share: "\u00a7bDu teilst deinen Rucksack jetzt mit deinem Team."
    team-leave: "\u00a7aDu hast das Team verlassen."
    not-in-team: "\u00a7cDu bist in keinem Team."
    config-changed: "\u00a7aRucksack-Konfiguration aktualisiert."
    backpacks-disabled: "\u00a7cRucks채cke sind derzeit von einem Admin deaktiviert."
    admin-giveall: "\u00a7aItem an alle Rucks채cke verteilt."
    admin-enabled: "\u00a7aRucks채cke global aktiviert."
    admin-disabled: "\u00a7cRucks채cke global deaktiviert."
