name: SimpleBackpack
main: org.vwtfafa.backpack.Backpack
version: 2.0.0
api-version: 1.20
commands:
  backpack:
    description: Opens your personal backpack (configurable size, persistent)
    usage: /backpack
  invite:
    description: Invite a player to your team to share your backpack
    usage: /invite <player>
  team:
    description: Show your team members
    usage: /team
  backpackconfig:
    description: Open the backpack configuration GUI
    usage: /backpackconfig
authors: ["vwtfafa"]
description: A simple backpack plugin for Minecraft 1.20+ (Paper/Spigot). Each player has a persistent, configurable backpack. Supports teams, GUI config, and multi-language messages.